Neos:
  Neos:
    fusion:
      autoInclude:
        'TechDivision.NodeTypes.FlexColumnLayouts': true
    userInterface:
      translation:
        autoInclude:
          TechDivision.NodeTypes.FlexColumnLayouts:
            - 'Main'
            - 'NodeTypes/*'
